### ISSUE TITLE
what k8s release this shim use?

### ISSUE THREAD

**Issue by kitianFresh** [cloudera/yunikorn-k8shim#14]
following has some err in Goland

    // create a volume binder (needs the informers)
	ctx.volumeBinder = volumebinder.NewVolumeBinder(
		ctx.kubeClient.GetClientSet(),
		ctx.nodeInformer, ctx.pvcInformer,
		ctx.pvInformer,
		ctx.storageInformer,
		ctx.conf.VolumeBindTimeout)

**Comment by yangwwei** [comment]
Hi @kitianFresh 

We are currently depending on `v1.14.3`. If you are using GoLand, could you turn on `vgo` from the preference and then see if this error goes away?

**Comment by kitianFresh** [comment]
![image](https://user-images.githubusercontent.com/8846958/61890157-786e4500-af39-11e9-83e3-61e682c3cf7c.png)

**Comment by kitianFresh** [comment]
when i use vgo, there are more errors
![image](https://user-images.githubusercontent.com/8846958/61890579-53c69d00-af3a-11e9-8194-579361421234.png)

**Comment by yangwwei** [comment]
This should be a setup issue.
When you have `vgo` disabled, GoLand is searching dependencies from GOPATH, it looks like it falls to the wrong `vendor` dir in your workspace to find K8s dependencies.
When you have `vgo` enabled, you saw these errors because you don't have them downloaded via `go mod`. Can you try to run `make build` from the project, then `go mod` should automatically download these dependencies for you. 
Let me know if this works for you.

**Comment by yangwwei** [comment]
Any updates on this @kitianFresh ?

**Comment by kitianFresh** [comment]
i solved it by disable the vendoring mode option when i enable vgo. thanks very much. @yangwwei

**Comment by yangwwei** [comment]
Awesome, thx @kitianFresh
